/**
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateCoauthorDTO } from './createCoauthorDTO';


/**
 * Class representing a DTO for creating songs in the application.
 */
export interface CreateSongDTO { 
    userIdAdded: number;
    /**
     * Author's name (doesn't have to exist)
     */
    authorName: string;
    /**
     * Category
     */
    categoryId: number;
    title: string;
    coauthors: Array<CreateCoauthorDTO>;
    lyrics: string;
    guitarTabs: string;
    trivia?: string;
    tags: Array<string>;
}
