/**
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorDTO } from './authorDTO';
import { CategoryDTO } from './categoryDTO';
import { SongCoauthorDTO } from './songCoauthorDTO';
import { TagDTO } from './tagDTO';


export interface SongDTO { 
    author?: AuthorDTO;
    averageRating?: number;
    category?: CategoryDTO;
    coauthors: Array<SongCoauthorDTO>;
    creationTime?: string;
    guitarTabs?: string;
    id: number;
    lyrics?: string;
    tags: Array<TagDTO>;
    title: string;
    trivia?: string;
}
