/**
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateGuitarCordDTO } from './createGuitarCordDTO';


/**
 * Class representing a DTO for creating lines of verses.
 */
export interface CreateLineDTO { 
    chorus?: boolean;
    /**
     * Order of the line in the song
     */
    order?: number;
    /**
     * Content of the line in the song
     */
    content?: string;
    cords?: Array<CreateGuitarCordDTO>;
}
