/**
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Class representing a DTO for creating guitar cords for lines of the songs.
 */
export interface CreateGuitarCordDTO { 
    /**
     * Content of the cord in the song
     */
    content?: string;
    /**
     * Position in the line of the cord.
     */
    position?: number;
}
