/**
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SongDTO { 
    addedBy?: number;
    authorId: number;
    averageRating?: number;
    categoryId: number;
    id: number;
    isAwaiting?: boolean;
    title: string;
    trivia?: string;
}
