export * from './adminResource.service';
import { AdminResourceService } from './adminResource.service';
export * from './authenticationResource.service';
import { AuthenticationResourceService } from './authenticationResource.service';
export * from './authorResource.service';
import { AuthorResourceService } from './authorResource.service';
export * from './awaitingSongResource.service';
import { AwaitingSongResourceService } from './awaitingSongResource.service';
export * from './categoryResource.service';
import { CategoryResourceService } from './categoryResource.service';
export * from './guitarCordResource.service';
import { GuitarCordResourceService } from './guitarCordResource.service';
export * from './lineResource.service';
import { LineResourceService } from './lineResource.service';
export * from './playlistResource.service';
import { PlaylistResourceService } from './playlistResource.service';
export * from './songCoauthorResource.service';
import { SongCoauthorResourceService } from './songCoauthorResource.service';
export * from './songResource.service';
import { SongResourceService } from './songResource.service';
export * from './tagResource.service';
import { TagResourceService } from './tagResource.service';
export * from './userResource.service';
import { UserResourceService } from './userResource.service';
export * from './userRoleResource.service';
import { UserRoleResourceService } from './userRoleResource.service';
export * from './userSongRatingResource.service';
import { UserSongRatingResourceService } from './userSongRatingResource.service';
export * from './verseResource.service';
import { VerseResourceService } from './verseResource.service';
export const APIS = [AdminResourceService, AuthenticationResourceService, AuthorResourceService, AwaitingSongResourceService, CategoryResourceService, GuitarCordResourceService, LineResourceService, PlaylistResourceService, SongCoauthorResourceService, SongResourceService, TagResourceService, UserResourceService, UserRoleResourceService, UserSongRatingResourceService, VerseResourceService];
