/**
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { GuitarCordDTO } from '../model/guitarCordDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class GuitarCordResourceService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getAllGuitarCords
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllGuitarCordsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<GuitarCordDTO>>;
    public getAllGuitarCordsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GuitarCordDTO>>>;
    public getAllGuitarCordsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GuitarCordDTO>>>;
    public getAllGuitarCordsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<GuitarCordDTO>>(`${this.basePath}/api/guitar-cords`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getGuitarCordById
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getGuitarCordByIdUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<GuitarCordDTO>;
    public getGuitarCordByIdUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GuitarCordDTO>>;
    public getGuitarCordByIdUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GuitarCordDTO>>;
    public getGuitarCordByIdUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getGuitarCordByIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<GuitarCordDTO>(`${this.basePath}/api/guitar-cords/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateGuitarCord
     * 
     * @param guitarCordDTO guitarCordDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateGuitarCordUsingPUT(guitarCordDTO: GuitarCordDTO, observe?: 'body', reportProgress?: boolean): Observable<GuitarCordDTO>;
    public updateGuitarCordUsingPUT(guitarCordDTO: GuitarCordDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GuitarCordDTO>>;
    public updateGuitarCordUsingPUT(guitarCordDTO: GuitarCordDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GuitarCordDTO>>;
    public updateGuitarCordUsingPUT(guitarCordDTO: GuitarCordDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (guitarCordDTO === null || guitarCordDTO === undefined) {
            throw new Error('Required parameter guitarCordDTO was null or undefined when calling updateGuitarCordUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<GuitarCordDTO>(`${this.basePath}/api/guitar-cords`,
            guitarCordDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
