/**
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateGuitarCordDTO } from '../model/createGuitarCordDTO';
import { GuitarCordDTO } from '../model/guitarCordDTO';
import { LineDTO } from '../model/lineDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class LineResourceService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * addGuitarCord
     * 
     * @param cord cord
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addGuitarCordUsingPATCH(cord: CreateGuitarCordDTO, id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public addGuitarCordUsingPATCH(cord: CreateGuitarCordDTO, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public addGuitarCordUsingPATCH(cord: CreateGuitarCordDTO, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public addGuitarCordUsingPATCH(cord: CreateGuitarCordDTO, id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cord === null || cord === undefined) {
            throw new Error('Required parameter cord was null or undefined when calling addGuitarCordUsingPATCH.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling addGuitarCordUsingPATCH.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch<any>(`${this.basePath}/api/lines/${encodeURIComponent(String(id))}/add-guitar-cord`,
            cord,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllLines
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllLinesUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<LineDTO>>;
    public getAllLinesUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<LineDTO>>>;
    public getAllLinesUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<LineDTO>>>;
    public getAllLinesUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<LineDTO>>(`${this.basePath}/api/lines`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getLineById
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLineByIdUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<LineDTO>;
    public getLineByIdUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LineDTO>>;
    public getLineByIdUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LineDTO>>;
    public getLineByIdUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getLineByIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<LineDTO>(`${this.basePath}/api/lines/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getLineCords
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLineCordsUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<Array<GuitarCordDTO>>;
    public getLineCordsUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GuitarCordDTO>>>;
    public getLineCordsUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GuitarCordDTO>>>;
    public getLineCordsUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getLineCordsUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<GuitarCordDTO>>(`${this.basePath}/api/lines/${encodeURIComponent(String(id))}/guitar-cords`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * removeGuitarCord
     * 
     * @param cordId cordId
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public removeGuitarCordUsingPATCH(cordId: number, id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public removeGuitarCordUsingPATCH(cordId: number, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public removeGuitarCordUsingPATCH(cordId: number, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public removeGuitarCordUsingPATCH(cordId: number, id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cordId === null || cordId === undefined) {
            throw new Error('Required parameter cordId was null or undefined when calling removeGuitarCordUsingPATCH.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling removeGuitarCordUsingPATCH.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.patch<any>(`${this.basePath}/api/lines/${encodeURIComponent(String(id))}/remove-guitar-cord/${encodeURIComponent(String(cordId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateLine
     * 
     * @param lineDTO lineDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateLineUsingPUT(lineDTO: LineDTO, observe?: 'body', reportProgress?: boolean): Observable<LineDTO>;
    public updateLineUsingPUT(lineDTO: LineDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LineDTO>>;
    public updateLineUsingPUT(lineDTO: LineDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LineDTO>>;
    public updateLineUsingPUT(lineDTO: LineDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (lineDTO === null || lineDTO === undefined) {
            throw new Error('Required parameter lineDTO was null or undefined when calling updateLineUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<LineDTO>(`${this.basePath}/api/lines`,
            lineDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
