export * from './authorRestController.service';
import { AuthorRestControllerService } from './authorRestController.service';
export * from './categoryRestController.service';
import { CategoryRestControllerService } from './categoryRestController.service';
export * from './playlistRestController.service';
import { PlaylistRestControllerService } from './playlistRestController.service';
export * from './songCoauthorRestController.service';
import { SongCoauthorRestControllerService } from './songCoauthorRestController.service';
export * from './songRestController.service';
import { SongRestControllerService } from './songRestController.service';
export * from './tagRestController.service';
import { TagRestControllerService } from './tagRestController.service';
export * from './userRestController.service';
import { UserRestControllerService } from './userRestController.service';
export * from './userRoleRestController.service';
import { UserRoleRestControllerService } from './userRoleRestController.service';
export * from './userSongRatingRestController.service';
import { UserSongRatingRestControllerService } from './userSongRatingRestController.service';
export const APIS = [AuthorRestControllerService, CategoryRestControllerService, PlaylistRestControllerService, SongCoauthorRestControllerService, SongRestControllerService, TagRestControllerService, UserRestControllerService, UserRoleRestControllerService, UserSongRatingRestControllerService];
