export * from './adminResource.service';
import { AdminResourceService } from './adminResource.service';
export * from './authorResource.service';
import { AuthorResourceService } from './authorResource.service';
export * from './awaitingSongResource.service';
import { AwaitingSongResourceService } from './awaitingSongResource.service';
export * from './categoryResource.service';
import { CategoryResourceService } from './categoryResource.service';
export * from './playlistResource.service';
import { PlaylistResourceService } from './playlistResource.service';
export * from './songCoauthorResource.service';
import { SongCoauthorResourceService } from './songCoauthorResource.service';
export * from './songResource.service';
import { SongResourceService } from './songResource.service';
export * from './tagResource.service';
import { TagResourceService } from './tagResource.service';
export * from './userResource.service';
import { UserResourceService } from './userResource.service';
export * from './userRoleResource.service';
import { UserRoleResourceService } from './userRoleResource.service';
export * from './userSongRatingResource.service';
import { UserSongRatingResourceService } from './userSongRatingResource.service';
export const APIS = [AdminResourceService, AuthorResourceService, AwaitingSongResourceService, CategoryResourceService, PlaylistResourceService, SongCoauthorResourceService, SongResourceService, TagResourceService, UserResourceService, UserRoleResourceService, UserSongRatingResourceService];
